{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    {{- if .Values.isHttps }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- end }}
  name: python-http
  labels:
    {{- include "python-http.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /python-http
        backend:
          service:
            name: python-http
            port:
              name: http
{{- end }}
