{{- if .Values.nodeport }}
apiVersion: v1
kind: Service
metadata:
  name: python-http-nodeport
  labels:
    {{- include "python-http.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
  selector:
    app: python-http
{{- end }}