apiVersion: v1
kind: Service
metadata:
  name: python-http
  labels:
    {{- include "python-http.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app: python-http
